### ISSUE TITLE
bug in example.cpp

### ISSUE THREAD

**Issue by ahsalama** [EvanBalster/STL_mono_wedge#1]
Hi , Thasnks for the code, in any way I found (or I think I found) two bugs in the example file
first the operator> is not defined for struct Sample
and second the line 
`std::deque<float> max_wedge`;
should be 
`std::deque<Sample> max_wedge;`

Best regards
Ahmed Mostafa

**Comment by EvanBalster** [comment]
Fixed.  Give it a look.

**Comment by ahsalama** [comment]
Ithink you fixed the second one, but didn't add the operator > to the struct Sample

**Comment by EvanBalster** [comment]
Sorry, I read a little too quickly the first time.  Fixed.

**Comment by ahsalama** [comment]
Thanks, aside from that, the unit test file failed every test, do not know what is going there ..

**Comment by ahsalama** [comment]
will open a new issue with the unit test failure part
