### ISSUE TITLE
unittests fail on all tests

### ISSUE THREAD

**Issue by ahsalama** [EvanBalster/STL_mono_wedge#2]
When trying to execute unit tests, I think the max_wedge fails on all tests, I think something wrong with the update function (or the pop front!!)

**Comment by EvanBalster** [comment]
That's odd...  All the unit tests pass on my machine (OS X / Clang).  Can you double-check you're using the latest code from the repository?  It's also possible that some undefined behavior is responsible for the discrepancy.

**Comment by ahsalama** [comment]
I am working on Windows 7, visual studio 2015, so maybe there is some difference,  the first thing I noticed is 
sample = {t, value} ; 
Doesn't work (gives false value for time) 
and had to use 
sample.time =t;
This made it go well on minimum 
but still i get errors on maximum,  I noticed that the max_wedge size is always =1 !!

**Comment by EvanBalster** [comment]
OK, I'll give it a spin in Visual Studio tomorrow.  Thanks for bringing this to my attention.

Very weird about the brace-initialization not working...

**Comment by ahsalama** [comment]
Hi Evan, did you manage to test it in VS? 
Thanks

**Comment by EvanBalster** [comment]
Hello, Ahsalama —

Pardon the...  Slightly delayed reply.  I've been tinkering with this again lately and I'll give it a test in VS tomorrow.

**Comment by EvanBalster** [comment]
Looks like the tests pass in the latest commit:  https://github.com/EvanBalster/STL_mono_wedge/commit/d0aebccb6e3d3e0edc38ba0bccb74943ed04652b

I'm going to go ahead and close this for now.  Feel free to confirm.
