### ISSUE TITLE
Poor performance in some tests

### ISSUE THREAD

**Issue by lemire** [EvanBalster/STL_mono_wedge#3]
Nice project! I like how elegant the code is.

I added a wrapped version of your code to a small benchmark I do... You can see my thin wrapper there:

https://github.com/lemire/runningmaxmin/blob/master/runningmaxmin.h#L432-L447

I just benchmark how long it takes to run the constructor. The performance is not good. I wonder whether you could have a look to make sure that I put your implementation in the best light, performance-wise...

Here are my numbers (you might need to scroll to the extreme right to see all numbers, timings for your code is given in the last column):

```
$ ./runningmaxmin
# we report timings (in seconds) so lower is better
Generating sine waves.
Using a min/max width of 3
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.015417       0.082492       0.037198       0.083176        0.01871       0.052559       0.032996       0.256408
Using a min/max width of 4
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.018405       0.083609       0.039338       0.077945       0.019584       0.055848       0.034447       0.267839
Using a min/max width of 5
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.015367       0.076276       0.034978       0.065592       0.017649       0.049925        0.03066       0.241275
Using a min/max width of 6
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.020868       0.080584       0.036746       0.066239       0.018735        0.05249       0.032036        0.25328
Using a min/max width of 7
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.022835       0.079981        0.03657       0.063469       0.018643       0.052583       0.032313       0.254965
Using a min/max width of 8
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.025178         0.0823       0.038173       0.063162        0.01903       0.053479       0.032826       0.257789
Using a min/max width of 9
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.022291       0.078316       0.035624       0.060435       0.018352       0.050822       0.031194       0.244385
Using a min/max width of 10
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
        0.02537       0.076714        0.03525       0.058362       0.018272       0.049871       0.030643       0.239334
Using a min/max width of 11
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.028196       0.079439       0.036236       0.060809       0.018731       0.051851       0.031396       0.245782
Using a min/max width of 12
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.028566       0.076489        0.03519       0.059557       0.018234        0.04989       0.030792       0.239211
Using a min/max width of 13
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.031233       0.081097       0.036788       0.063145       0.019495       0.052802       0.032379        0.25321
Using a min/max width of 14
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
        0.03269        0.08005       0.036366       0.062363       0.019152       0.051925       0.031852       0.252438
Using a min/max width of 15
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.035656       0.083557       0.036233        0.06319       0.019271       0.051688       0.031708       0.250158
Using a min/max width of 16
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.040112       0.086176       0.037604       0.062264       0.019858       0.053027       0.032203       0.256026
Using a min/max width of 17
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.044628       0.091512       0.038673        0.06713       0.020825       0.055062       0.033461       0.262869
Using a min/max width of 18
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.049232       0.094877       0.039353       0.069502       0.021397        0.05631       0.033948       0.266815
Using a min/max width of 19
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.051598       0.095745       0.039207       0.069719       0.021401       0.056139       0.034051         0.2694
Using a min/max width of 20
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.053689        0.09468       0.039402       0.068278        0.02114       0.054957       0.033463       0.261587
Using a min/max width of 21
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.058259       0.095942       0.038823       0.067482       0.021473       0.055244         0.0334       0.259845
Using a min/max width of 22
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.061113       0.097134       0.038817       0.068339       0.021207       0.054842       0.033453       0.261006
Using a min/max width of 23
           slow        vanHerk         lemire      gilkimmel         bitmap   simplelemire        lemirew      monowedge
       0.066081       0.099847       0.040088       0.069587       0.022099       0.057168       0.034307       0.270607
```

**Comment by EvanBalster** [comment]
Hello, Daniel —

This repository was meant as a "quickie" reference implementation of the Lemire-Fenn algorithm.  As the name suggests it defers quite a lot to STL implementations (std::vector, std::lower_bound) which can differ quite a lot between compilers and compile modes.

That said, the difference is pretty striking!  I'm guessing something unusual (like memory allocation) accounts for the vast difference, in which case there might be some problem with my (hasty) implementation.

What compiler and OS did you use?

**Comment by lemire** [comment]
My tests were unscientific, done on my laptop... but you can easily reproduce them, I think :

```
$ git clone git@github.com:lemire/runningmaxmin.git
$ cd runningmaxmin
$ make
$ ./runningmaxmin
```

Your implementation is nice and general, so I would not care if it were slower... but it seems that the gap is large... so large that it is probably worth investigating.

**Comment by EvanBalster** [comment]
Yeah, it looks like the buffer is getting copied or isn't getting pruned or something.

**Comment by lemire** [comment]
I am sure that I am using your code stupidly.

**Comment by EvanBalster** [comment]
I really don't see anything wrong with your usage.  I think the best recourse would be to profile the code and work out where all that time is being spent.

**Comment by EvanBalster** [comment]
Hmm.  Interestingly, the stack trace places quite a lot of the performance usage in `std::deque::erase` (this is under clang).  Deep inspection suggests libc's implementation may have N^2 complexity — so maybe I'll stop using it!!  Some of the other STL algorithms I'm deferring to are also suspiciously heavy.  Even after fixes it's likely a slim, C-style ringbuffer implementation of Lemire-Fenn would probably beat the pants off STL_mono_wedge.

<img width="1017" alt="screen shot 2017-10-31 at 5 48 20 pm" src="https://user-images.githubusercontent.com/13224671/32252547-d8a3d8e0-be63-11e7-9de4-651a1a68aeac.png">

**Comment by lemire** [comment]
There are efficient STL-like ring buffers, surely?

**Comment by EvanBalster** [comment]
I've poked at my code some more, replacing `erase` with `pop_back` and removing some unnecessary usage of iterator "jumps" which ought to yield some performance benefit.  Even after these changes it outperforms only the "slow" reference algorithm.  Anyway, I'll commit shortly.

An STL ring buffer implementation with a fixed capacity would achieve much higher performance than `std::deque`.  I recall making a note of that when I first wrote this algorithm.  There are some implementations out there but I haven't experimented with them.  To be honest, I would probably sidestep the STL and use C-like code for any DSP applications.  Too many caveats like what we've seen here.

**Comment by lemire** [comment]
If you beat the "slow" path for not super large windows, it is already a good step forward.

**Comment by EvanBalster** [comment]
It beats the "slow" path for some larger windows.  Remarkably, though, the `deque::push_back` calls alone amount for more time usage than the entire lemire bitmap algorithm.

I'm not so busy this evening, so I might throw together a simple STL-compliant ringbuffer class, to see how that fares.

**Comment by lemire** [comment]
You might enjoy this blog post of mine...

* Do not waste time with STL vectors https://lemire.me/blog/2012/06/20/do-not-waste-time-with-stl-vectors/

**Comment by EvanBalster** [comment]
I suspect that in this case the issues arise from "abstraction tax".  `deque::erase` might be deferring to `std::erase` which in turn erases elements in order rather than specializing for the structure and its special cases.  I've heard of programming languages where simple operations like string concatenation have N^2 complexity for silly reasons like this — to say nothing of unnecessary calls to memory allocators.

Anyway, I've been poking at various ringbuffer implementations and ended up deciding to write up one of my own.  (boost::ringbuffer was the only clean implementation I found with the needed features, and it depends on far too many headers.)

I'll throw the new ringbuffer in the repo when it's done, and we'll see what it does for performance.

**Comment by lemire** [comment]
I'm looking forward to see the results.

**Comment by EvanBalster** [comment]
I've implemented the STL ringbuffer.  Performance improvements within the range of the tests are marginal (at least under clang's profiler) but seem to become more significant as the numbers go up.  I suspect the remaining performance discrepancies have to do with the memory access involved in traversing all the little bits of template code.

monowedge becomes somewhat more competitive with large window sizes:

```
# we report timings (in seconds) so lower is better
# window = 48000 whitesize = 192000 times = 1 doslow = 0
        vanHerk         lemire      gilkimmel   simplelemire        lemirew      monowedge
       0.019681        0.03723       0.021749       0.054086       0.018527       0.085402
```

Anyway, STL_mono_wedge was written as an exercise in illustrating Lemire-Fenn clearly by building on the standard C++ library.  Serious use-cases that need high throughput should probably use C-style algorithms with a smaller code footprint.  Also, Lemire-Fenn is designed to reduce the "peakiness" of the original Lemire algorithm with large window sizes.  Overall performance isn't necessarily going to be better than the original Lemire algorithm, and could even be worse.  (Haven't done the math on this.)

For intensive DSP applications with large window sizes it could be worth investigating a compact, optimized Lemire-Fenn algorithm implementation as a separate undertaking.

**Comment by lemire** [comment]
Thanks. Feel free to close the issue.

**Comment by EvanBalster** [comment]
This has been an educational exercise.  Thanks for bringing it to my attention.

If you decide to take a crack at a "compact" Lemire-Fenn implementation yourself, please let me know.  Otherwise I might do it at some point.

**Comment by lemire** [comment]
I might not get to it in a reasonable time.
