### ISSUE TITLE
Ethan Fenn's changes

### ISSUE THREAD

**Issue by marton78** [EvanBalster/STL_mono_wedge#4]
Hi,

could you add to the README Ethan Fenn's original post from the mailing list, where he proposes the changes to lower worst case complexity? It would be interesting for posterity (incl. me)...

Thanks!

**Comment by EvanBalster** [comment]
Done; added links and a transcript of Ethan's original ideation.  https://github.com/EvanBalster/STL_mono_wedge/commit/87c6ea2a1210540c82dc2aed951daa67526ac8b4
